using System.Collections.Generic;
using System.Text;

namespace OoplesFinance.StockIndicators.SourceGeneration;

/// <summary>
/// The preamble every generated file opens with, in one place rather than once per generator.
/// </summary>
/// <remarks>
/// <para>
/// Each generator emitted the same fifteen lines by hand - the auto-generated marker, the nullable
/// directive, the usings, the namespace, a summary and the class declaration - differing only in the names
/// inside them. Four copies of that is what took new-code duplication over the quality gate when the fourth
/// was added, and the gate was right: the copies are the same thing written out again, not four decisions
/// that happen to agree.
/// </para>
/// <para>
/// This says it once and takes the names as arguments. The output is unchanged, which is the point - the
/// generated files are compared byte for byte before and after, so this is a refactor of the generators and
/// not of anything they produce.
/// </para>
/// </remarks>
internal static class GeneratedSource
{
    /// <summary>Opens a generated static class, leaving the builder inside its body.</summary>
    /// <param name="usings">Namespaces to import, in the order they should appear.</param>
    /// <param name="namespaceName">The file-scoped namespace to declare.</param>
    /// <param name="summary">The lines of the class summary, without their comment markers.</param>
    /// <param name="className">The class to declare.</param>
    public static StringBuilder OpenStaticClass(
        IEnumerable<string> usings, string namespaceName, IEnumerable<string> summary, string className)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var import in usings)
        {
            sb.AppendLine($"using {import};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");

        foreach (var line in summary)
        {
            sb.AppendLine($"/// {line}");
        }

        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        return sb;
    }
}
