using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace OoplesFinance.StockIndicators.SourceGeneration;

/// <summary>
/// Roslyn source generator that creates typed indicator methods for IndicatorCatalog.
/// Scans the IndicatorName enum and generates methods for indicators that don't have hand-written overloads.
/// </summary>
[Generator]
public class IndicatorCatalogGenerator : IIncrementalGenerator
{
    // Hand-written indicators that should not be generated
    private static readonly HashSet<string> HandWrittenIndicators = new(StringComparer.OrdinalIgnoreCase)
    {
        "SimpleMovingAverage",
        "ExponentialMovingAverage",
        "RelativeStrengthIndex",
        "MovingAverageConvergenceDivergence",
        "BollingerBands",
        "AverageTrueRange",
        "AverageDirectionalIndex",
        "StochasticOscillator",
        "WeightedMovingAverage",
        "HullMovingAverage",
        "TripleExponentialMovingAverage",
        "DoubleExponentialMovingAverage",
        "CommodityChannelIndex",
        "WilliamsR",
        "RateOfChange",
        "MomentumOscillator",
        "ParabolicSAR",
        "KeltnerChannels",
        "DonchianChannels",
        "VolumeWeightedAveragePrice",
        "OnBalanceVolume",
        "MoneyFlowIndex",
        "IchimokuCloud",
        "StandardDeviation",
        "TrueStrengthIndex"
    };

    // Multi-output indicators that need special Result types
    private static readonly Dictionary<string, string[]> MultiOutputIndicators = new(StringComparer.OrdinalIgnoreCase)
    {
        // Format: IndicatorName -> Output property names
        ["AroonOscillator"] = new[] { "Up", "Down", "Oscillator" },
        ["ElderRayIndex"] = new[] { "BullPower", "BearPower" },
        ["AlligatorIndex"] = new[] { "Jaw", "Teeth", "Lips" },
        ["GatorOscillator"] = new[] { "Upper", "Lower" },
        ["Trix"] = new[] { "Trix", "Signal" },
        ["PPO"] = new[] { "Ppo", "Signal", "Histogram" },
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Always generate a test file to verify the generator is running
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("IndicatorCatalog.Generated.Marker.g.cs", SourceText.From(
                "// Generator is running - marker file\n" +
                "namespace OoplesFinance.StockIndicators.Builder.Catalogs;\n" +
                "public sealed partial class IndicatorCatalog { /* Generated marker */ }\n",
                Encoding.UTF8));
        });

        // Find enum declarations named "IndicatorName"
        var enumDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateEnum(s),
                transform: static (ctx, _) => GetEnumSemanticTarget(ctx))
            .Where(static m => m is not null);

        // Combine with compilation
        var compilationAndEnums = context.CompilationProvider.Combine(enumDeclarations.Collect());

        // Generate source
        context.RegisterSourceOutput(compilationAndEnums, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateEnum(SyntaxNode node)
    {
        return node is EnumDeclarationSyntax enumDecl && enumDecl.Identifier.Text == "IndicatorName";
    }

    private static EnumDeclarationSyntax? GetEnumSemanticTarget(GeneratorSyntaxContext context)
    {
        var enumDecl = (EnumDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(enumDecl);

        if (symbol?.ContainingNamespace?.ToDisplayString() == "OoplesFinance.StockIndicators.Enums")
        {
            return enumDecl;
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<EnumDeclarationSyntax?> enums, SourceProductionContext context)
    {
        if (enums.IsDefaultOrEmpty)
        {
            return;
        }

        var enumDecl = enums.FirstOrDefault(e => e is not null);
        if (enumDecl is null)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using OoplesFinance.StockIndicators.Builder.Specs;");
        sb.AppendLine("using OoplesFinance.StockIndicators.Enums;");
        sb.AppendLine();
        sb.AppendLine("namespace OoplesFinance.StockIndicators.Builder.Catalogs;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated typed indicator methods for IndicatorCatalog.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed partial class IndicatorCatalog");
        sb.AppendLine("{");

        var generatedCount = 0;
        foreach (var member in enumDecl.Members)
        {
            var indicatorName = member.Identifier.Text;

            // Skip "None" and hand-written indicators
            if (indicatorName == "None" || HandWrittenIndicators.Contains(indicatorName))
            {
                continue;
            }

            // Generate method for this indicator
            var methodName = GetMethodName(indicatorName);
            var hasMultiOutput = MultiOutputIndicators.TryGetValue(indicatorName, out var outputs);

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Calculates {FormatIndicatorName(indicatorName)}.");
            sb.AppendLine($"    /// </summary>");

            if (hasMultiOutput && outputs is not null)
            {
                // Multi-output indicator - generate method returning result type
                var resultTypeName = $"{methodName}Result";
                sb.AppendLine($"    public {resultTypeName} {methodName}(int length = 14, SeriesHandle? input = null)");
                sb.AppendLine("    {");
                sb.AppendLine("        var series = input ?? Price();");
                sb.AppendLine("        var seriesKey = _builder.ResolveSeriesKey(series);");
                sb.AppendLine($"        var opts = new GenericIndicatorOptions(new object[] {{ length }});");

                for (int i = 0; i < outputs.Length; i++)
                {
                    var outputName = outputs[i].ToLowerInvariant();
                    var outputType = i == 0 ? "Primary" : (i == 1 ? "Signal" : "Histogram");
                    sb.AppendLine($"        var {outputName} = _builder.AddIndicator(IndicatorSpecs.Create(IndicatorName.{indicatorName}, opts, IndicatorOutput.{outputType}), series, seriesKey, null);");
                }

                var outputArgs = string.Join(", ", outputs.Select(o => o.ToLowerInvariant()));
                sb.AppendLine($"        return new {resultTypeName}({outputArgs});");
                sb.AppendLine("    }");
            }
            else
            {
                // Single-output indicator
                sb.AppendLine($"    public SeriesHandle {methodName}(int length = 14, SeriesHandle? input = null, IndicatorKey? key = null)");
                sb.AppendLine("    {");
                sb.AppendLine("        var series = input ?? Price();");
                sb.AppendLine($"        var spec = IndicatorSpecs.Create(IndicatorName.{indicatorName}, new GenericIndicatorOptions(new object[] {{ length }}), IndicatorOutput.Primary);");
                sb.AppendLine("        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);");
                sb.AppendLine("    }");
            }

            generatedCount++;
        }

        sb.AppendLine("}");

        // Generate result types for multi-output indicators
        if (MultiOutputIndicators.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("// Multi-output result types");
            foreach (var kvp in MultiOutputIndicators)
            {
                if (HandWrittenIndicators.Contains(kvp.Key))
                {
                    continue;
                }

                var methodName = GetMethodName(kvp.Key);
                var outputs = kvp.Value;
                var resultTypeName = $"{methodName}Result";

                sb.AppendLine();
                sb.AppendLine($"/// <summary>");
                sb.AppendLine($"/// {FormatIndicatorName(kvp.Key)} multi-output result.");
                sb.AppendLine($"/// </summary>");
                sb.AppendLine($"public readonly struct {resultTypeName}");
                sb.AppendLine("{");

                // Constructor
                var ctorParams = string.Join(", ", outputs.Select(o => $"SeriesHandle {o.ToLowerInvariant()}"));
                sb.AppendLine($"    public {resultTypeName}({ctorParams})");
                sb.AppendLine("    {");
                foreach (var output in outputs)
                {
                    sb.AppendLine($"        {output} = {output.ToLowerInvariant()};");
                }
                sb.AppendLine("    }");
                sb.AppendLine();

                // Properties
                foreach (var output in outputs)
                {
                    sb.AppendLine($"    /// <summary>Gets the {output} series.</summary>");
                    sb.AppendLine($"    public SeriesHandle {output} {{ get; }}");
                }

                sb.AppendLine("}");
            }
        }

        context.AddSource("IndicatorCatalog.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetMethodName(string indicatorName)
    {
        // Remove common prefixes/suffixes for cleaner method names
        var name = indicatorName;

        // Handle special naming conventions
        if (name.StartsWith("_"))
        {
            name = name.TrimStart('_');
        }

        // Handle numbered prefixes like "3HMA" -> "Hma3"
        if (char.IsDigit(name[0]))
        {
            var numberPart = new string(name.TakeWhile(char.IsDigit).ToArray());
            var restPart = name.Substring(numberPart.Length);
            name = restPart + numberPart;
        }

        return name;
    }

    private static string FormatIndicatorName(string indicatorName)
    {
        // Convert PascalCase to space-separated words
        var sb = new StringBuilder();
        foreach (var c in indicatorName)
        {
            if (char.IsUpper(c) && sb.Length > 0)
            {
                sb.Append(' ');
            }
            sb.Append(c);
        }
        return sb.ToString();
    }
}
