using OoplesFinance.StockIndicators.Builder.Specs;
using OoplesFinance.StockIndicators.Enums;
using OoplesFinance.StockIndicators.Streaming;

namespace OoplesFinance.StockIndicators.Builder.Catalogs;

/// <summary>
/// Catalog of available indicators for the builder.
/// Provides typed methods for common indicators and generic access to all 750+ indicators.
/// Additional typed methods are generated by the source generator.
/// </summary>
public sealed partial class IndicatorCatalog
{
    private readonly StockIndicatorBuilder _builder;

    internal IndicatorCatalog(StockIndicatorBuilder builder)
    {
        _builder = builder;
    }

    #region Generic Indicator Access

    /// <summary>
    /// Calculates any indicator by name using reflection-based dispatch.
    /// This provides access to all 750+ indicators in the library.
    /// </summary>
    /// <param name="name">The indicator name from the IndicatorName enum.</param>
    /// <param name="parameters">Optional parameters for the indicator (varies by indicator).</param>
    /// <param name="input">Optional input series. If null, uses default price series.</param>
    /// <param name="key">Optional key for named lookup.</param>
    /// <returns>A SeriesHandle for the primary output of the indicator.</returns>
    /// <remarks>
    /// Use GetIndicatorParameters() to discover what parameters an indicator accepts.
    /// Common parameter types include: int (length), double (multiplier), MovingAvgType.
    /// </remarks>
    public SeriesHandle Calculate(IndicatorName name, object[]? parameters = null, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(name, new GenericIndicatorOptions(parameters ?? Array.Empty<object>()), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Gets the parameter information for a specific indicator.
    /// </summary>
    /// <param name="name">The indicator name.</param>
    /// <returns>Array of parameter info, or null if indicator not found.</returns>
    /// <remarks>
    /// V2 Note: This method uses the V1 reflection-based IndicatorInvoker for backwards compatibility.
    /// In V2, indicators are defined via StatefulIndicator classes with strongly-typed constructors.
    /// Consider using the source-generated catalog methods instead.
    /// </remarks>
    [Obsolete("V1 API - use V2 StatefulIndicator constructors directly. Will be removed in next major version.")]
    public static System.Reflection.ParameterInfo[]? GetIndicatorParameters(IndicatorName name)
    {
        // V1 fallback - this will eventually be removed
#pragma warning disable CS0618 // Suppress obsolete warning for internal use
        return IndicatorInvoker.GetParameters(name);
#pragma warning restore CS0618
    }

    /// <summary>
    /// Checks if an indicator is supported by the V2 StatefulIndicator factory.
    /// </summary>
    /// <param name="name">The indicator name.</param>
    /// <returns>True if the indicator can be calculated via V2.</returns>
    public static bool IsIndicatorSupported(IndicatorName name)
    {
        // V2 approach: Try to create the state - if it works, it's supported
        try
        {
            var spec = IndicatorSpecs.Create(name, new GenericIndicatorOptions(Array.Empty<object>()), IndicatorOutput.Primary);
            var state = StatefulIndicatorFactory.Create(spec);
            // If we got here, it's supported. Dispose if needed.
            if (state is IDisposable disposable)
            {
                disposable.Dispose();
            }
            return true;
        }
        catch (NotSupportedException)
        {
            return false;
        }
    }

    /// <summary>
    /// Gets all supported indicator names.
    /// </summary>
    /// <returns>Collection of all supported indicator names.</returns>
    /// <remarks>
    /// V2 Note: Returns all IndicatorName enum values. Use IsIndicatorSupported()
    /// to check if a specific indicator has a V2 StatefulIndicator implementation.
    /// </remarks>
    public static IReadOnlyCollection<IndicatorName> GetSupportedIndicators()
    {
        // Return all indicator names - the factory will throw if one isn't supported
        return Enum.GetValues(typeof(IndicatorName))
            .Cast<IndicatorName>()
            .Where(n => n != IndicatorName.None)
            .ToList()
            .AsReadOnly();
    }

    #endregion

    /// <summary>
    /// Gets the default price series handle.
    /// </summary>
    public SeriesHandle Price()
    {
        return _builder.GetDefaultSeriesHandle();
    }

    /// <summary>
    /// Gets the price series handle from a named data source.
    /// Use this for multi-stock indicators that compare against a market index.
    /// </summary>
    /// <param name="sourceName">The name of the data source (registered via AddDataSource).</param>
    /// <returns>A SeriesHandle for the named source's price data.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the named source is not found.</exception>
    /// <example>
    /// <code>
    /// // Register market data for comparison
    /// builder.AddDataSource("market", IndicatorDataSource.FromBatch(spyData));
    ///
    /// // Use in indicator configuration
    /// builder.ConfigureIndicators(catalog => {
    ///     var marketPrice = catalog.Price("market");
    ///     var rsmk = catalog.RSMKIndicator(marketPrice, 90, 3);
    /// });
    /// </code>
    /// </example>
    public SeriesHandle Price(string sourceName)
    {
        var source = _builder.GetNamedSource(sourceName);
        if (source is null)
        {
            throw new InvalidOperationException(
                $"Data source '{sourceName}' not found. Register it first with builder.AddDataSource(\"{sourceName}\", source).");
        }

        // Create a series key for the named source
        var symbol = new SymbolId(sourceName);
        var timeframe = _builder.ResolveDefaultSeriesKey().Timeframe;
        var key = new SeriesKey(symbol, timeframe);
        return _builder.GetOrCreateBaseSeries(key);
    }

    /// <summary>
    /// Creates a chain for a specific symbol and timeframe.
    /// </summary>
    public IndicatorChain For(SymbolId symbol, BarTimeframe timeframe)
    {
        var key = new SeriesKey(symbol, timeframe);
        var baseSeries = _builder.GetOrCreateBaseSeries(key);
        return new IndicatorChain(this, baseSeries);
    }

    /// <summary>
    /// Creates a chain for a specific symbol with default timeframe.
    /// </summary>
    public IndicatorChain For(SymbolId symbol)
    {
        var defaultKey = _builder.ResolveDefaultSeriesKey();
        return For(symbol, defaultKey.Timeframe);
    }

    /// <summary>
    /// Creates a chain from an existing series.
    /// </summary>
    public IndicatorChain Then(SeriesHandle input)
    {
        return new IndicatorChain(this, input);
    }

    /// <summary>
    /// Calculates Simple Moving Average.
    /// </summary>
    public SeriesHandle Sma(int length, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        return _builder.AddIndicator(IndicatorSpecs.Sma(length), series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Exponential Moving Average.
    /// </summary>
    public SeriesHandle Ema(int length, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        return _builder.AddIndicator(IndicatorSpecs.Ema(length), series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Relative Strength Index with default Wilder smoothing.
    /// </summary>
    public SeriesHandle Rsi(int length = 14, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        return _builder.AddIndicator(IndicatorSpecs.Rsi(length), series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Relative Strength Index with configurable smoothing method.
    /// </summary>
    /// <param name="length">The RSI period length.</param>
    /// <param name="maType">The smoothing method. Use WildersSmoothingMethod (original) or SimpleMovingAverage (Cutler variant).</param>
    /// <param name="input">Optional input series. If null, uses default price series.</param>
    /// <param name="key">Optional key for named lookup.</param>
    /// <returns>A SeriesHandle for the RSI values.</returns>
    /// <remarks>
    /// RSI Variants:
    /// - Wilder (original, 1978): Uses Wilder's smoothing method, slower response
    /// - Cutler: Uses simple moving average, more responsive to price changes
    /// </remarks>
    public SeriesHandle Rsi(int length, MovingAvgType maType, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        return _builder.AddIndicator(IndicatorSpecs.Rsi(length, maType), series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates MACD (Moving Average Convergence Divergence).
    /// </summary>
    public MacdResult Macd(int fastLength = 12, int slowLength = 26, int signalLength = 9,
        SeriesHandle? input = null, IndicatorKey? primaryKey = null, IndicatorKey? signalKey = null, IndicatorKey? histogramKey = null)
    {
        var series = input ?? Price();
        var seriesKey = _builder.ResolveSeriesKey(series);
        var primary = _builder.AddIndicator(IndicatorSpecs.Macd(fastLength, slowLength, signalLength, IndicatorOutput.Primary),
            series, seriesKey, primaryKey);
        var signal = _builder.AddIndicator(IndicatorSpecs.Macd(fastLength, slowLength, signalLength, IndicatorOutput.Signal),
            series, seriesKey, signalKey);
        var histogram = _builder.AddIndicator(IndicatorSpecs.Macd(fastLength, slowLength, signalLength, IndicatorOutput.Histogram),
            series, seriesKey, histogramKey);

        return new MacdResult(primary, signal, histogram);
    }

    /// <summary>
    /// Calculates Bollinger Bands.
    /// </summary>
    public BollingerBandsResult BollingerBands(int length = 20, double stdDevMult = 2, SeriesHandle? input = null,
        IndicatorKey? upperKey = null, IndicatorKey? middleKey = null, IndicatorKey? lowerKey = null)
    {
        var series = input ?? Price();
        var seriesKey = _builder.ResolveSeriesKey(series);
        var upper = _builder.AddIndicator(IndicatorSpecs.BollingerBands(length, stdDevMult, IndicatorOutput.UpperBand),
            series, seriesKey, upperKey);
        var middle = _builder.AddIndicator(IndicatorSpecs.BollingerBands(length, stdDevMult, IndicatorOutput.MiddleBand),
            series, seriesKey, middleKey);
        var lower = _builder.AddIndicator(IndicatorSpecs.BollingerBands(length, stdDevMult, IndicatorOutput.LowerBand),
            series, seriesKey, lowerKey);

        return new BollingerBandsResult(upper, middle, lower);
    }

    /// <summary>
    /// Calculates Average True Range with default Wilder smoothing.
    /// </summary>
    public SeriesHandle Atr(int length = 14, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        return _builder.AddIndicator(IndicatorSpecs.Atr(length), series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Average True Range with configurable smoothing method.
    /// </summary>
    /// <param name="length">The ATR period length.</param>
    /// <param name="maType">The smoothing method. Use WildersSmoothingMethod (original), SimpleMovingAverage, or ExponentialMovingAverage.</param>
    /// <param name="input">Optional input series. If null, uses default price series.</param>
    /// <param name="key">Optional key for named lookup.</param>
    /// <returns>A SeriesHandle for the ATR values.</returns>
    /// <remarks>
    /// ATR Variants:
    /// - Wilder (original, 1978): Uses Wilder's smoothing method
    /// - SMA: Uses simple moving average of true range
    /// - EMA: Uses exponential moving average of true range
    /// </remarks>
    public SeriesHandle Atr(int length, MovingAvgType maType, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        return _builder.AddIndicator(IndicatorSpecs.Atr(length, maType), series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Average Directional Index.
    /// </summary>
    public SeriesHandle Adx(int length = 14, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        return _builder.AddIndicator(IndicatorSpecs.Adx(length), series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Stochastic Oscillator.
    /// </summary>
    public StochasticResult Stochastic(int kLength = 14, int dLength = 3, SeriesHandle? input = null,
        IndicatorKey? kKey = null, IndicatorKey? dKey = null)
    {
        var series = input ?? Price();
        var seriesKey = _builder.ResolveSeriesKey(series);
        var k = _builder.AddIndicator(IndicatorSpecs.Stochastic(kLength, dLength, IndicatorOutput.Primary),
            series, seriesKey, kKey);
        var d = _builder.AddIndicator(IndicatorSpecs.Stochastic(kLength, dLength, IndicatorOutput.Signal),
            series, seriesKey, dKey);
        return new StochasticResult(k, d);
    }

    /// <summary>
    /// Calculates Weighted Moving Average.
    /// </summary>
    public SeriesHandle Wma(int length, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.WeightedMovingAverage, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Hull Moving Average.
    /// </summary>
    public SeriesHandle Hma(int length, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.HullMovingAverage, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Triple Exponential Moving Average (TEMA).
    /// </summary>
    public SeriesHandle Tema(int length, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.TripleExponentialMovingAverage, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Double Exponential Moving Average (DEMA).
    /// </summary>
    public SeriesHandle Dema(int length, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.DoubleExponentialMovingAverage, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Commodity Channel Index.
    /// </summary>
    public SeriesHandle Cci(int length = 20, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.CommodityChannelIndex, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Williams %R.
    /// </summary>
    public SeriesHandle WilliamsR(int length = 14, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.WilliamsR, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Rate of Change.
    /// </summary>
    public SeriesHandle Roc(int length = 12, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.RateOfChange, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Momentum Oscillator.
    /// </summary>
    public SeriesHandle Momentum(int length = 10, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.MomentumOscillator, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Parabolic SAR.
    /// </summary>
    public SeriesHandle Sar(double accelerationStart = 0.02, double accelerationMax = 0.2, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.ParabolicSAR, new GenericIndicatorOptions(new object[] { accelerationStart, accelerationMax }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Keltner Channels.
    /// </summary>
    public KeltnerChannelResult KeltnerChannels(int length = 20, double multiplier = 2, SeriesHandle? input = null,
        IndicatorKey? upperKey = null, IndicatorKey? middleKey = null, IndicatorKey? lowerKey = null)
    {
        var series = input ?? Price();
        var seriesKey = _builder.ResolveSeriesKey(series);
        var upper = _builder.AddIndicator(
            IndicatorSpecs.Create(IndicatorName.KeltnerChannels, new GenericIndicatorOptions(new object[] { length, multiplier }), IndicatorOutput.UpperBand),
            series, seriesKey, upperKey);
        var middle = _builder.AddIndicator(
            IndicatorSpecs.Create(IndicatorName.KeltnerChannels, new GenericIndicatorOptions(new object[] { length, multiplier }), IndicatorOutput.MiddleBand),
            series, seriesKey, middleKey);
        var lower = _builder.AddIndicator(
            IndicatorSpecs.Create(IndicatorName.KeltnerChannels, new GenericIndicatorOptions(new object[] { length, multiplier }), IndicatorOutput.LowerBand),
            series, seriesKey, lowerKey);
        return new KeltnerChannelResult(upper, middle, lower);
    }

    /// <summary>
    /// Calculates Donchian Channels.
    /// </summary>
    public DonchianChannelResult DonchianChannels(int length = 20, SeriesHandle? input = null,
        IndicatorKey? upperKey = null, IndicatorKey? middleKey = null, IndicatorKey? lowerKey = null)
    {
        var series = input ?? Price();
        var seriesKey = _builder.ResolveSeriesKey(series);
        var upper = _builder.AddIndicator(
            IndicatorSpecs.Create(IndicatorName.DonchianChannels, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.UpperBand),
            series, seriesKey, upperKey);
        var middle = _builder.AddIndicator(
            IndicatorSpecs.Create(IndicatorName.DonchianChannels, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.MiddleBand),
            series, seriesKey, middleKey);
        var lower = _builder.AddIndicator(
            IndicatorSpecs.Create(IndicatorName.DonchianChannels, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.LowerBand),
            series, seriesKey, lowerKey);
        return new DonchianChannelResult(upper, middle, lower);
    }

    /// <summary>
    /// Calculates VWAP (Volume Weighted Average Price).
    /// </summary>
    public SeriesHandle Vwap(SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.VolumeWeightedAveragePrice, new GenericIndicatorOptions(Array.Empty<object>()), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates On Balance Volume.
    /// </summary>
    public SeriesHandle Obv(SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.OnBalanceVolume, new GenericIndicatorOptions(Array.Empty<object>()), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Money Flow Index.
    /// </summary>
    public SeriesHandle Mfi(int length = 14, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.MoneyFlowIndex, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates Ichimoku Cloud.
    /// </summary>
    public IchimokuResult Ichimoku(int tenkanLength = 9, int kijunLength = 26, int senkouBLength = 52, SeriesHandle? input = null)
    {
        var series = input ?? Price();
        var seriesKey = _builder.ResolveSeriesKey(series);
        var opts = new GenericIndicatorOptions(new object[] { tenkanLength, kijunLength, senkouBLength });
        var tenkanSen = _builder.AddIndicator(IndicatorSpecs.Create(IndicatorName.IchimokuCloud, opts, IndicatorOutput.Primary), series, seriesKey, null);
        var kijunSen = _builder.AddIndicator(IndicatorSpecs.Create(IndicatorName.IchimokuCloud, opts, IndicatorOutput.Signal), series, seriesKey, null);
        var senkouSpanA = _builder.AddIndicator(IndicatorSpecs.Create(IndicatorName.IchimokuCloud, opts, IndicatorOutput.UpperBand), series, seriesKey, null);
        var senkouSpanB = _builder.AddIndicator(IndicatorSpecs.Create(IndicatorName.IchimokuCloud, opts, IndicatorOutput.LowerBand), series, seriesKey, null);
        var chikouSpan = _builder.AddIndicator(IndicatorSpecs.Create(IndicatorName.IchimokuCloud, opts, IndicatorOutput.Histogram), series, seriesKey, null);
        return new IchimokuResult(tenkanSen, kijunSen, senkouSpanA, senkouSpanB, chikouSpan);
    }

    /// <summary>
    /// Calculates Standard Deviation.
    /// </summary>
    public SeriesHandle StdDev(int length = 20, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.StandardDeviation, new GenericIndicatorOptions(new object[] { length }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Calculates True Strength Index.
    /// </summary>
    public SeriesHandle Tsi(int longLength = 25, int shortLength = 13, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var series = input ?? Price();
        var spec = IndicatorSpecs.Create(IndicatorName.TrueStrengthIndex, new GenericIndicatorOptions(new object[] { longLength, shortLength }), IndicatorOutput.Primary);
        return _builder.AddIndicator(spec, series, _builder.ResolveSeriesKey(series), key);
    }

    /// <summary>
    /// Creates a formula combining two series.
    /// </summary>
    public SeriesHandle Formula(SeriesHandle left, SeriesHandle right, FormulaOp op)
    {
        return _builder.AddFormula(left, right, op switch
        {
            FormulaOp.Add => (x, y) => x + y,
            FormulaOp.Subtract => (x, y) => x - y,
            FormulaOp.Multiply => (x, y) => x * y,
            FormulaOp.Divide => (x, y) => y == 0 ? double.NaN : x / y,
            _ => (x, y) => double.NaN
        });
    }

    /// <summary>
    /// Creates a formula combining two series with a custom function.
    /// </summary>
    public SeriesHandle Formula(SeriesHandle left, SeriesHandle right, Func<double, double, double> formula)
    {
        return _builder.AddFormula(left, right, formula);
    }

    #region Multi-Stock Comparison Indicators

    /// <summary>
    /// Calculates RSMK (Relative Strength Mansfield-Kostelich) Indicator.
    /// Compares a stock's performance against a market index.
    /// </summary>
    /// <param name="marketPrice">The market/benchmark price series (e.g., S&amp;P 500).</param>
    /// <param name="length">The lookback period for the ratio calculation. Default is 90.</param>
    /// <param name="smoothLength">The smoothing length for the EMA. Default is 3.</param>
    /// <param name="input">Optional input series for the stock. Uses default price if null.</param>
    /// <param name="key">Optional key for named lookup.</param>
    /// <returns>A SeriesHandle for the RSMK indicator values.</returns>
    /// <example>
    /// <code>
    /// builder.AddDataSource("market", IndicatorDataSource.FromBatch(spyData));
    /// builder.ConfigureIndicators(catalog => {
    ///     var marketPrice = catalog.Price("market");
    ///     var rsmk = catalog.RSMKIndicator(marketPrice, 90, 3);
    /// });
    /// </code>
    /// </example>
    public SeriesHandle RSMKIndicator(SeriesHandle marketPrice, int length = 90, int smoothLength = 3,
        SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var stockPrice = input ?? Price();
        var spec = IndicatorSpecs.CreateMultiStock(
            IndicatorName.RSMKIndicator,
            new MultiStockIndicatorOptions(length, smoothLength, MovingAvgType.ExponentialMovingAverage),
            IndicatorOutput.Primary);
        return _builder.AddMultiStockIndicator(spec, stockPrice, marketPrice, _builder.ResolveSeriesKey(stockPrice), key);
    }

    /// <summary>
    /// Calculates Compare Price Momentum Oscillator (CPMO).
    /// Compares a stock's momentum against a market index.
    /// </summary>
    /// <param name="marketPrice">The market/benchmark price series.</param>
    /// <param name="length1">First smoothing period. Default is 20.</param>
    /// <param name="length2">Second smoothing period. Default is 35.</param>
    /// <param name="signalLength">Signal line length. Default is 10.</param>
    /// <param name="input">Optional input series for the stock. Uses default price if null.</param>
    /// <param name="key">Optional key for named lookup.</param>
    public SeriesHandle ComparePriceMomentumOscillator(SeriesHandle marketPrice, int length1 = 20, int length2 = 35,
        int signalLength = 10, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var stockPrice = input ?? Price();
        var spec = IndicatorSpecs.CreateMultiStock(
            IndicatorName.ComparePriceMomentumOscillator,
            new MultiStockIndicatorOptions(length1, length2, signalLength, MovingAvgType.ExponentialMovingAverage),
            IndicatorOutput.Primary);
        return _builder.AddMultiStockIndicator(spec, stockPrice, marketPrice, _builder.ResolveSeriesKey(stockPrice), key);
    }

    /// <summary>
    /// Calculates Kaufman Stress Indicator.
    /// Measures stress relative to market volatility.
    /// </summary>
    /// <param name="marketPrice">The market/benchmark price series.</param>
    /// <param name="length">The lookback period. Default is 60.</param>
    /// <param name="input">Optional input series for the stock. Uses default price if null.</param>
    /// <param name="key">Optional key for named lookup.</param>
    public SeriesHandle KaufmanStressIndicator(SeriesHandle marketPrice, int length = 60,
        SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var stockPrice = input ?? Price();
        var spec = IndicatorSpecs.CreateMultiStock(
            IndicatorName.KaufmanStressIndicator,
            new MultiStockIndicatorOptions(length),
            IndicatorOutput.Primary);
        return _builder.AddMultiStockIndicator(spec, stockPrice, marketPrice, _builder.ResolveSeriesKey(stockPrice), key);
    }

    /// <summary>
    /// Calculates Relative Normalized Volatility.
    /// Compares volatility relative to a market index.
    /// </summary>
    /// <param name="marketPrice">The market/benchmark price series.</param>
    /// <param name="length">The lookback period. Default is 14.</param>
    /// <param name="input">Optional input series for the stock. Uses default price if null.</param>
    /// <param name="key">Optional key for named lookup.</param>
    public SeriesHandle RelativeNormalizedVolatility(SeriesHandle marketPrice, int length = 14,
        SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var stockPrice = input ?? Price();
        var spec = IndicatorSpecs.CreateMultiStock(
            IndicatorName.RelativeNormalizedVolatility,
            new MultiStockIndicatorOptions(length, MovingAvgType.SimpleMovingAverage),
            IndicatorOutput.Primary);
        return _builder.AddMultiStockIndicator(spec, stockPrice, marketPrice, _builder.ResolveSeriesKey(stockPrice), key);
    }

    /// <summary>
    /// Calculates Relative Strength 3D Indicator.
    /// Multi-period relative strength comparison against a market index.
    /// </summary>
    /// <param name="marketPrice">The market/benchmark price series.</param>
    /// <param name="length1">First period length. Default is 4.</param>
    /// <param name="length2">Second period length. Default is 7.</param>
    /// <param name="length3">Third period length. Default is 10.</param>
    /// <param name="length4">Fourth period length. Default is 15.</param>
    /// <param name="length5">Fifth period length. Default is 30.</param>
    /// <param name="input">Optional input series for the stock. Uses default price if null.</param>
    /// <param name="key">Optional key for named lookup.</param>
    public SeriesHandle RelativeStrength3DIndicator(SeriesHandle marketPrice, int length1 = 4, int length2 = 7,
        int length3 = 10, int length4 = 15, int length5 = 30, SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var stockPrice = input ?? Price();
        var spec = IndicatorSpecs.CreateMultiStock(
            IndicatorName.RelativeStrength3DIndicator,
            new MultiStockIndicatorOptions(length1, length2, length3, length4, length5, MovingAvgType.ExponentialMovingAverage),
            IndicatorOutput.Primary);
        return _builder.AddMultiStockIndicator(spec, stockPrice, marketPrice, _builder.ResolveSeriesKey(stockPrice), key);
    }

    /// <summary>
    /// Calculates Sector Rotation Model.
    /// Identifies sector rotation relative to market.
    /// </summary>
    /// <param name="marketPrice">The market/benchmark price series.</param>
    /// <param name="length1">First smoothing period. Default is 25.</param>
    /// <param name="length2">Second smoothing period. Default is 75.</param>
    /// <param name="input">Optional input series for the stock. Uses default price if null.</param>
    /// <param name="key">Optional key for named lookup.</param>
    public SeriesHandle SectorRotationModel(SeriesHandle marketPrice, int length1 = 25, int length2 = 75,
        SeriesHandle? input = null, IndicatorKey? key = null)
    {
        var stockPrice = input ?? Price();
        var spec = IndicatorSpecs.CreateMultiStock(
            IndicatorName.SectorRotationModel,
            new MultiStockIndicatorOptions(length1, length2, MovingAvgType.ExponentialMovingAverage),
            IndicatorOutput.Primary);
        return _builder.AddMultiStockIndicator(spec, stockPrice, marketPrice, _builder.ResolveSeriesKey(stockPrice), key);
    }

    #endregion

    internal void ApplyDefaults(IndicatorSelection selection)
    {
        if (selection == null)
        {
            return;
        }

        switch (selection.Preset)
        {
            case IndicatorPreset.None:
                // No default indicators - optimal for performance
                return;
            case IndicatorPreset.All:
            case IndicatorPreset.Core:
                var price = Price();
                Sma(20, price, IndicatorKey.Sma);
                Rsi(14, price, IndicatorKey.Rsi);
                Macd(12, 26, 9, price, IndicatorKey.Macd, IndicatorKey.MacdSignal, IndicatorKey.MacdHistogram);
                BollingerBands(20, 2, price, IndicatorKey.BollingerUpper, IndicatorKey.BollingerMiddle, IndicatorKey.BollingerLower);
                break;
            case IndicatorPreset.Only:
                if (selection.Include == null)
                {
                    return;
                }

                var baseSeries = Price();
                for (var i = 0; i < selection.Include.Count; i++)
                {
                    switch (selection.Include[i])
                    {
                        case IndicatorName.SimpleMovingAverage:
                            Sma(20, baseSeries, IndicatorKey.Sma);
                            break;
                        case IndicatorName.RelativeStrengthIndex:
                            Rsi(14, baseSeries, IndicatorKey.Rsi);
                            break;
                        case IndicatorName.MovingAverageConvergenceDivergence:
                            Macd(12, 26, 9, baseSeries, IndicatorKey.Macd, IndicatorKey.MacdSignal, IndicatorKey.MacdHistogram);
                            break;
                        case IndicatorName.BollingerBands:
                            BollingerBands(20, 2, baseSeries, IndicatorKey.BollingerUpper, IndicatorKey.BollingerMiddle,
                                IndicatorKey.BollingerLower);
                            break;
                    }
                }

                break;
        }
    }
}

/// <summary>
/// Fluent chain for indicators on a specific series.
/// </summary>
public readonly struct IndicatorChain
{
    private readonly IndicatorCatalog _catalog;
    private readonly SeriesHandle _input;

    internal IndicatorChain(IndicatorCatalog catalog, SeriesHandle input)
    {
        _catalog = catalog;
        _input = input;
    }

    /// <summary>
    /// Gets the input series handle.
    /// </summary>
    public SeriesHandle Input => _input;

    /// <summary>
    /// Calculates Simple Moving Average.
    /// </summary>
    public SeriesHandle Sma(int length, IndicatorKey? key = null)
    {
        return _catalog.Sma(length, _input, key);
    }

    /// <summary>
    /// Calculates Exponential Moving Average.
    /// </summary>
    public SeriesHandle Ema(int length, IndicatorKey? key = null)
    {
        return _catalog.Ema(length, _input, key);
    }

    /// <summary>
    /// Calculates Relative Strength Index.
    /// </summary>
    public SeriesHandle Rsi(int length = 14, IndicatorKey? key = null)
    {
        return _catalog.Rsi(length, _input, key);
    }

    /// <summary>
    /// Calculates MACD.
    /// </summary>
    public MacdResult Macd(int fastLength = 12, int slowLength = 26, int signalLength = 9,
        IndicatorKey? primaryKey = null, IndicatorKey? signalKey = null, IndicatorKey? histogramKey = null)
    {
        return _catalog.Macd(fastLength, slowLength, signalLength, _input, primaryKey, signalKey, histogramKey);
    }

    /// <summary>
    /// Calculates Bollinger Bands.
    /// </summary>
    public BollingerBandsResult BollingerBands(int length = 20, double stdDevMult = 2,
        IndicatorKey? upperKey = null, IndicatorKey? middleKey = null, IndicatorKey? lowerKey = null)
    {
        return _catalog.BollingerBands(length, stdDevMult, _input, upperKey, middleKey, lowerKey);
    }

    /// <summary>
    /// Calculates ATR.
    /// </summary>
    public SeriesHandle Atr(int length = 14, IndicatorKey? key = null)
    {
        return _catalog.Atr(length, _input, key);
    }

    /// <summary>
    /// Calculates ADX.
    /// </summary>
    public SeriesHandle Adx(int length = 14, IndicatorKey? key = null)
    {
        return _catalog.Adx(length, _input, key);
    }
}
